### ISSUE TITLE
Plugin fails on project validation

### ISSUE THREAD

**Issue by powerTea-cz** [bubblefoil/p4u-worklogger#22]
As I started to use the plugin, no issue could be loaded due to failing project validation which fails on error every time. Removing this validation fixed the script for me. The error tells me:

`{"errorMessages":[],"errors":{"projectKey":"Projekt 'Norwegian Energy Certificate System' používá tento klíč projektu."}}`

**Comment by bubblefoil** [comment]
This happens when looking up a JIRA project key at jira.eu and jira.com to see which domain should be used. JIRA API can only validate project existence in a way that if it exists, it returns an error. That's why [code at line 759](https://github.com/bubblefoil/p4u-worklogger/blob/83aa0b24da04d070f15584b03f5ac75c3ed9953f/worklogger.user.js#L759) checks for a specific error message in responses.
This error message was in English, that is probably the reason why it fails now with the translated message.
If jira.eu is no longer used by anyone, this whole peace of code could be deleted.

**Comment by bubblefoil** [comment]
Fixed in 2.10. Removed jira.eu support altogether.
